Importing Dependencies

In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression
import joblib

In [3]:
housing_data=pd.read_csv("kenya_affordable_housing_dataset.csv")
housing_data.head()

,house_id,housing_category,house_type,location,size_sqm,cost_per_sqm_ksh,construction_cost_ksh,financing_cost_ksh,markup_ksh,government_subsidy_ksh,final_price_ksh,interest_rate_pct,repayment_years,monthly_repayment_ksh,buyer_monthly_income_ksh,housing_levy_contribution_ksh,affordability_ratio,affordable
0,KE-0001,Affordable,2-Bedroom,Kisumu,54,53617.0,2895300.0,579100.0,496800.0,278000.0,3693200.0,6.0,20,26460.0,47500,710.0,0.557,0
1,KE-0002,Market-Rate,1-Bedroom,Westlands,36,92954.0,3346300.0,669300.0,803100.0,0.0,4818700.0,9.0,25,40440.0,395200,5930.0,0.102,1
2,KE-0003,Affordable,1-Bedroom,Kisumu,33,54498.0,1798400.0,359700.0,308600.0,172600.0,2294100.0,6.0,25,14780.0,44000,660.0,0.336,0
3,KE-0004,Affordable,1-Bedroom,Kasarani,32,52836.0,1690700.0,338100.0,290100.0,162300.0,2156600.0,6.0,30,12930.0,132600,1990.0,0.098,1
4,KE-0005,Social,2-Bedroom,Nairobi CBD,54,60409.0,3262100.0,652400.0,368000.0,587200.0,3695300.0,3.0,30,15580.0,16500,250.0,0.944,0

In [4]:
housing_data.columns

Index(['house_id', 'housing_category', 'house_type', 'location', 'size_sqm',
       'cost_per_sqm_ksh', 'construction_cost_ksh', 'financing_cost_ksh',
       'markup_ksh', 'government_subsidy_ksh', 'final_price_ksh',
       'interest_rate_pct', 'repayment_years', 'monthly_repayment_ksh',
       'buyer_monthly_income_ksh', 'housing_levy_contribution_ksh',
       'affordability_ratio', 'affordable'],
      dtype='str')

In [7]:
housing_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   house_id                       1000 non-null   str
 1   housing_category               1000 non-null   str
 2   house_type                     1000 non-null   str
 3   location                       1000 non-null   str
 4   size_sqm                       1000 non-null   int64
 5   cost_per_sqm_ksh               1000 non-null   float64
 6   construction_cost_ksh          1000 non-null   float64
 7   financing_cost_ksh             1000 non-null   float64
 8   markup_ksh                     1000 non-null   float64
 9   government_subsidy_ksh         1000 non-null   float64
 10  final_price_ksh                1000 non-null   float64
 11  interest_rate_pct              1000 non-null   float64
 12  repayment_years                1000 non-null   int64
 13  monthly_repayment_ksh          1000 non-null   float64
 14  buyer_monthly_income_ksh       1000 non-null   int64
 15  housing_levy_contribution_ksh  1000 non-null   float64
 16  affordability_ratio            1000 non-null   float64
 17  affordable                     1000 non-null   int64
dtypes: float64(10), int64(4), str(4)
memory usage: 140.8 KB

In [8]:
missing_values=housing_data.isnull().sum().sort_values(ascending=False)
missing_values

house_id                         0
housing_category                 0
house_type                       0
location                         0
size_sqm                         0
cost_per_sqm_ksh                 0
construction_cost_ksh            0
financing_cost_ksh               0
markup_ksh                       0
government_subsidy_ksh           0
final_price_ksh                  0
interest_rate_pct                0
repayment_years                  0
monthly_repayment_ksh            0
buyer_monthly_income_ksh         0
housing_levy_contribution_ksh    0
affordability_ratio              0
affordable                       0
dtype: int64

In [9]:
# Checking cateorical columns
categorical_columns=housing_data.select_dtypes(include=["object", "category"]).columns
print("Categorical Columns: ")
print(categorical_columns)

Categorical Columns:
Index(['house_id', 'housing_category', 'house_type', 'location'], dtype='str')

C:\Users\Hi\AppData\Local\Temp\ipykernel_8884\82581711.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns=housing_data.select_dtypes(include=["object", "category"]).columns

In [10]:
# Encode categorical columns
label_encoder=LabelEncoder()
categorical_columns=[
    'house_id', 
    'housing_category', 
    'house_type', 
    'location'
]
for col in categorical_columns:
    housing_data[col]=label_encoder.fit_transform(housing_data[col])
housing_data.head()

,house_id,housing_category,house_type,location,size_sqm,cost_per_sqm_ksh,construction_cost_ksh,financing_cost_ksh,markup_ksh,government_subsidy_ksh,final_price_ksh,interest_rate_pct,repayment_years,monthly_repayment_ksh,buyer_monthly_income_ksh,housing_levy_contribution_ksh,affordability_ratio,affordable
0,0,0,1,4,54,53617.0,2895300.0,579100.0,496800.0,278000.0,3693200.0,6.0,20,26460.0,47500,710.0,0.557,0
1,1,1,0,9,36,92954.0,3346300.0,669300.0,803100.0,0.0,4818700.0,9.0,25,40440.0,395200,5930.0,0.102,1
2,2,0,0,4,33,54498.0,1798400.0,359700.0,308600.0,172600.0,2294100.0,6.0,25,14780.0,44000,660.0,0.336,0
3,3,0,0,2,32,52836.0,1690700.0,338100.0,290100.0,162300.0,2156600.0,6.0,30,12930.0,132600,1990.0,0.098,1
4,4,2,1,6,54,60409.0,3262100.0,652400.0,368000.0,587200.0,3695300.0,3.0,30,15580.0,16500,250.0,0.944,0

In [11]:
# Checking for features correlated with target variables-final_price_ksh
corr_matrix=housing_data.corr()
corr_with_target=corr_matrix['final_price_ksh'].sort_values(ascending=False)
print('Correlated features with final_price_ksh: ', corr_with_target.head(20))

Correlated features with final_price_ksh:  final_price_ksh                  1.000000
financing_cost_ksh               0.987912
construction_cost_ksh            0.987912
markup_ksh                       0.974179
monthly_repayment_ksh            0.956849
size_sqm                         0.743660
cost_per_sqm_ksh                 0.629225
interest_rate_pct                0.522971
housing_levy_contribution_ksh    0.494465
buyer_monthly_income_ksh         0.494443
location                         0.140527
affordability_ratio              0.060877
affordable                       0.011066
repayment_years                  0.003313
government_subsidy_ksh          -0.017636
house_id                        -0.042065
house_type                      -0.045257
housing_category                -0.105270
Name: final_price_ksh, dtype: float64

In [12]:
# New dataset with features that correlation is greater than 0.25
high_corr_features=corr_with_target[abs(corr_with_target)>0.25].index
housing_data=housing_data[high_corr_features]
housing_data

,final_price_ksh,financing_cost_ksh,construction_cost_ksh,markup_ksh,monthly_repayment_ksh,size_sqm,cost_per_sqm_ksh,interest_rate_pct,housing_levy_contribution_ksh,buyer_monthly_income_ksh
0,3693200.0,579100.0,2895300.0,496800.0,26460.0,54,53617.0,6.0,710.0,47500
1,4818700.0,669300.0,3346300.0,803100.0,40440.0,36,92954.0,9.0,5930.0,395200
2,2294100.0,359700.0,1798400.0,308600.0,14780.0,33,54498.0,6.0,660.0,44000
3,2156600.0,338100.0,1690700.0,290100.0,12930.0,32,52836.0,6.0,1990.0,132600
4,3695300.0,652400.0,3262100.0,368000.0,15580.0,54,60409.0,3.0,250.0,16500
...,...,...,...,...,...,...,...,...,...,...
995,1300100.0,229500.0,1147700.0,129500.0,7210.0,20,57387.0,3.0,170.0,11200
996,6642000.0,922500.0,4612500.0,1107000.0,55740.0,56,82366.0,9.0,7040.0,469100
997,5270300.0,930500.0,4652400.0,524800.0,22220.0,78,59646.0,3.0,210.0,13900
998,2413600.0,335200.0,1676100.0,402300.0,24480.0,22,76185.0,9.0,5150.0,343600
999,2731600.0,428300.0,2141400.0,367500.0,23050.0,56,38240.0,6.0,1640.0,109300

In [19]:
# Visualizing features with high correlation to final_price_ksh using heatmap
# plt.figure(figsize=(10, 8))
# sns.heatmap(housing_data[corr_with_target[corr_with_target>0.25].index].corr(), annot=True, cmaps='Reds', fmt='.2f')
# plt.title("Correlation Heatmap of high correlation features")
# plt.show()

In [22]:
# Creating X and y variables
X=housing_data.drop(columns=['final_price_ksh'])
y=housing_data['final_price_ksh']

# Splitting the data into training and training sets
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
X

,financing_cost_ksh,construction_cost_ksh,markup_ksh,monthly_repayment_ksh,size_sqm,cost_per_sqm_ksh,interest_rate_pct,housing_levy_contribution_ksh,buyer_monthly_income_ksh
0,579100.0,2895300.0,496800.0,26460.0,54,53617.0,6.0,710.0,47500
1,669300.0,3346300.0,803100.0,40440.0,36,92954.0,9.0,5930.0,395200
2,359700.0,1798400.0,308600.0,14780.0,33,54498.0,6.0,660.0,44000
3,338100.0,1690700.0,290100.0,12930.0,32,52836.0,6.0,1990.0,132600
4,652400.0,3262100.0,368000.0,15580.0,54,60409.0,3.0,250.0,16500
...,...,...,...,...,...,...,...,...,...
995,229500.0,1147700.0,129500.0,7210.0,20,57387.0,3.0,170.0,11200
996,922500.0,4612500.0,1107000.0,55740.0,56,82366.0,9.0,7040.0,469100
997,930500.0,4652400.0,524800.0,22220.0,78,59646.0,3.0,210.0,13900
998,335200.0,1676100.0,402300.0,24480.0,22,76185.0,9.0,5150.0,343600
999,428300.0,2141400.0,367500.0,23050.0,56,38240.0,6.0,1640.0,109300

In [24]:
y

0      3693200.0
1      4818700.0
2      2294100.0
3      2156600.0
4      3695300.0
         ...
995    1300100.0
996    6642000.0
997    5270300.0
998    2413600.0
999    2731600.0
Name: final_price_ksh, Length: 1000, dtype: float64

In [25]:
# Creating and training the model
model=LinearRegression()
model.fit(X_train, y_train)

# Predicting target variable
y_pred=model.predict(X_test)

# Evaluating the model
mae=mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error: ", mae)
r2_score_value=r2_score(y_test, y_pred)
print("R2 Score: ", r2_score_value)

Mean Absolute Error:  560.4824669701193
R2 Score:  0.9999998115836857

In [26]:
# Saving model in a file named affordable_price_model.pkl
joblib.dump(model, "affordable_price_model.pkl")

['affordable_price_model.pkl']